---

security:
  ignore-vulnerabilities:
    52495:
      reason: setuptools comes from Debian
      expires: '2025-01-31'
    62044:
      reason: Mercurial is not used in this project and pip comes from Debian
      expires: '2026-03-31'
    70612:
      reason: jinja2 is not used by sdkmanager, nor any dependencies I could find via debtree and pipdeptree.
      expires: '2026-05-31'
